### ISSUE TITLE
A problem about build

### ISSUE THREAD

**Issue by coolalexzb** [obachem/kmc2#3]
Hello , when I input the command that  "pip  install setup.py" , a error occurred . Where should the "kmc2.c" be put ? Please help me . Thank you very much .
<img width="607" alt="image" src="https://cloud.githubusercontent.com/assets/19755247/22535536/b9411a1a-e936-11e6-87d7-3bbee68fe019.png">

**Comment by vmarkovtsev** [comment]
1. Clone this project.

2. Edit `setup.py` and remove `extra_compile_args=['-O3']`. It is hardcoded for GCC-compatible compilers, and yours is not (Windows sucks).

3. Execute `pip install .`
